### PR TITLE
imp: allow for open structs

### PR DESCRIPTION
**Pull request by Pacman99**
All default behavior and original api is preserved, functionality of structs only changes if a `false` bool is passed at any point to the function.

**Tests**
```
nix-repl> (struct false { name = string; }) { name = "hi";a=5; }
{ a = 5; name = "hi"; }
nix-repl> (struct { name = string; }) { name = "hi";a=5; }       
error: expected 'anon'-struct, but found:
       unexpected struct field 'a'
nix-repl> (struct "test" false { name = string; }) { name = "hi";a=5; }
{ a = 5; name = "hi"; }
nix-repl> (struct "test" true { name = string; }) { name = "hi";a=5; }
error: expected 'test'-struct, but found:
       unexpected struct field 'a'
nix-repl> (struct "test" { name = string; }) { name = "hi";a=5; }      
error: expected 'test'-struct, but found:
       unexpected struct field 'a'
```

### CODE REVIEW

**Comment by Pacman99** [comment]
perhaps it would be better if there was just a new `openStruct` type? `struct false { ... }` is confusing to read.

**Comment by Pacman99** [comment]
Second commit moves open structs into a separate `openStruct`. So commit for whichever is preferred can be merged. I'm in favor of the latter.

**Comment by Pacman99** [comment]
**Example/Test**
```
nix-repl> (struct { a = string; }) { a = "hi"; }
{ a = "hi"; }

nix-repl> (struct { a = string; }) { a = 5; }    
error: expected 'anon'-struct, but found:
       field 'a': expected type 'string', but value '5' is of type 'int'

nix-repl> (struct "hi" { a = string; }) { a = 5; }
error: expected 'hi'-struct, but found:
       field 'a': expected type 'string', but value '5' is of type 'int'

nix-repl> (openStruct "hi" { a = string; }) { a = 5; } 
error: expected 'hi'-struct, but found:
       field 'a': expected type 'string', but value '5' is of type 'int'

nix-repl> (openStruct "hi" { a = string; }) { a = "hi"; }
{ a = "hi"; }

nix-repl> (openStruct "hi" { a = string; }) { a = "hi"; b = 5;}
{ a = "hi"; b = 5; }

nix-repl> (struct { a = string; }) { a = "hi"; b = 5;}          
error: expected 'anon'-struct, but found:
       unexpected struct field 'b'
```

**Comment by blaggacao** [comment]
Thank you! That's a great addition!

**Pull request merged**
